title: Patrick Hobusch
logo: /assets/img/avatar_patrick.png
description: DevOps Engineer, Open Source Enthusiast, Embedded / IoT as a Hobby, M.Sc. Computer Science
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
